Litch/Loot_the_Universe_COMs_to_Slaughter_Shaft.bl3hotfix, Litch/temp
Basegame class mods will now drop from Slaughter Shaft
=> Loot the Universe COMs to Slaughter Shaft

lollixlii/Fixed Weapon Cards/Fixed Weapon Cards.bl3hotfix
=> Update Fixed Weapon Cards.bl3hotfix

Elektrohund/UI_Mods/Small_Hud.bl3hotfix, Elektrohund/UI_Mods/Small_Hud_NoXPBar.bl3hotfix, Elektrohund/UI_Mods/Small_Hud_NoXPBar_NoCrosshair.bl3hotfix
=> Added Iron Bear

python_mod_helpers/hotfixgenerator/README.MD, python_mod_helpers/hotfixgenerator/__info_function__.py, python_mod_helpers/hotfixgenerator/__interface__.py, python_mod_helpers/hotfixgenerator/_global_lists.py, python_mod_helpers/hotfixgenerator/bl3data.py
Things have come a long way since I first started working on this. At first, this was a passion project for me, something that I wanted to make for myself. Now my project is part of the official bl3 mods repo and I'm part of this modding community. I never thought this would happen. I love working on this project and I hope that other people in the community love this project too
=> More Progress

Lonemasterino/Remove Health Gates.bl3hotfix
First real thing I'm doing here, let me know if anything is missing.
=> Create Remove Health Gates.bl3hotfix

python_mod_helpers/hotfixgenerator/__hotfix_control.py, python_mod_helpers/hotfixgenerator/__info_function__.py, python_mod_helpers/hotfixgenerator/__interface__.py, python_mod_helpers/hotfixgenerator/_global_lists.py, python_mod_helpers/hotfixgenerator/bl3data.py
The program now has even more functionality that implements even more functions from bl3hotfixmods
=> More functionality 

skruntskrunt/raid/Makefile, skruntskrunt/raid/README.md, skruntskrunt/raid/raid.bl3hotfix, skruntskrunt/raid/raid.bl3hotfix.HEAD, skruntskrunt/raid/raid.py
Minor bug fix, demoskagons were spawning too much loot. Matty Crawly wasn't working. Arbalest now fixed.
=> Raid Mod Bug Fix 1.4.1

TheNiTrex/BuffedProjectedShields/buffed_projected_shields.bl3hotfix
A mod that buffs the projected shield augment.
=> Add BuffedProjectedShields

TheGigaMaster/Major Weapon Overhaul/README.md, TheGigaMaster/Major Weapon Overhaul/Weapon_Balance_Overhaul.bl3hotfix
fixed a few guns and updated the description to include changes
=> weapon overhaul fixes

TheGigaMaster/Major Weapon Overhaul/README.md, TheGigaMaster/Major Weapon Overhaul/Weapon_Balance_Overhaul.bl3hotfix
adjusted some of the values of a few weapons as they felt overpowered and updated the description to match those changes
=> Weapon Overhaul Balancing

TheGigaMaster/Guardian Angel Nerf/Guardian Angel Nerf 250%.bl3hotfix, TheGigaMaster/Guardian Angel Nerf/Guardian Angel Nerf 400%.bl3hotfix, TheGigaMaster/Guardian Angel Nerf/README.md, TheGigaMaster/README.md
Nerf's the damage value provided by the Guardian Angel. There's 2 versions based on feedback I received while testing it.
=> Guardian Angel Nerf Mod Upload

Novenic/Map Defogger/README.md, Novenic/Map Defogger/map_defogger.bl3hotfix
Adds new folder for mods and an initial mod
=> bl3mods Pull Request

Poïpoï/Legendary Arms Race.bl3hotfix
Reverts BLCM/bl3mods#103
Sheesh, I didn't even notice this wasn't the original author.  If you want to make a change to someone's mod, you'd need to check the license and then upload a different copy under your own name, if the license permits.  Reverting this back to its original state!
=> Revert "Update Legendary Arms Race.bl3hotfix"

Phenom/Legendary_Price_Scaling.bl3hotfix, Phenom/README.md, Phenom/TVHM_Scale_From_Level1.bl3hotfix, Phenom/Unlimited_Bank_Backpack.bl3hotfix
Add Unlimited Bank & Backpack mod
Add TVHM Scale From Level 1 mod
Add Legendary Price Scaling mod
=> Initial mods upload

Phenom/Beastmaster/Infinite_Fade_Away_Duration.bl3hotfix, Phenom/Beastmaster/Infinite_Gamma_Burst_Duration.bl3hotfix, Phenom/Beastmaster/Instant_Pet_Respawn.bl3hotfix, Phenom/Beastmaster/No_Action_Skills_Cooldown_Beastmaster.bl3hotfix, Phenom/French Translations/README.md, Phenom/French Translations/TrialNames_Full_FR.bl3hotfix, Phenom/Unlimited_Bank_Backpack.bl3hotfix
Added Trial Names FR
Added No Action Skills Cooldown Beastmaster
Added Instant Pet Respawn
Added Infinite Fade Away Duration
Added Infinite Gamma Burst Duration
=> Added mods

Stygian Emperor/Consistent Mitigated Element Influence/README.md, Stygian Emperor/Consistent Mitigated Element Influence/StygianEmperor_Consistent_Mitigated_Element_Influence.bl3hotfix
My first BL3 mod, second try uploading it to GitHub. Hope I got it right this time.
=> Consistent & Mitigated Element Influence on Damage

Stygian Emperor/Consistent Mitigated Element Influence/README.md, Stygian Emperor/Consistent Mitigated Element Influence/StygianEmperor_Consistent_Mitigated_Element_Influence.bl3hotfix
=>  Consistent Mitigated Element Influence v1.0.2

Stygian Emperor/COV/FasterEquipSpeed/README.md, Stygian Emperor/COV/FasterEquipSpeed/StygianEmperor_COV_FasterEquipSpeed.bl3hotfix
Didn't like that the old image looked more like Hyperion branding than COV.
Added credit for the creator of the HD COV logo that was added.
Mod itself is unchanged.
=> Changed mod image and added credits

Freezer/Moze/Nuclear Moze.bl3hotfix
Tell me in the comments if you want "Big Surplus" to also do Radiation instead of Incendiary damage.
=> Create Nuclear Moze.bl3hotfix

Stygian Emperor/Moze/Iron Bear No Self Damage/README.md
had copied it over from an old readme
=> corrected date of release

DexManly/CCCTechspert/CCCTechspert.bl3hotfix, DexManly/CCCTechspert/README.md, DexManly/README.md
Adding new Zane Techspert classmod mod
=> CalmCoolCollected Techspert

CraZy Marty 695/Key_Eridium_Fabricator.bl3hotfix
This is the Key Eridium Fabricator hotfix mod that was posted on the modding discord cleaned up with descriptors added in to help people trying to edit it for themselves.
=> Key_Eridium_Fabricator Hotfix Upload

DexManly/ChestChanges/DiamondChest/DiamondChest_EridiumCost.bl3hotfix, DexManly/ChestChanges/DiamondChest/DiamondChest_FreeCost.bl3hotfix, DexManly/ChestChanges/DiamondChest/DiamondChest_GoldenKeyCost.bl3hotfix, DexManly/ChestChanges/DiamondChest/DiamondChest_MoneyCost.bl3hotfix, DexManly/ChestChanges/DiamondChest/README.md, DexManly/ChestChanges/GoldenChest/GoldenChest_EridiumCost.bl3hotfix, DexManly/ChestChanges/GoldenChest/GoldenChest_FreeCost.bl3hotfix, DexManly/ChestChanges/GoldenChest/GoldenChest_MoneyCost.bl3hotfix, DexManly/ChestChanges/GoldenChest/README.md
=> Adding Diamond and Golden loot economy changes

skruntskrunt/raid/raid.bl3hotfix, skruntskrunt/raid/raid.bl3hotfix.HEAD, skruntskrunt/raid/raid.py
=> Raid mod 1.4.1

CZ47/Takedown/Raid on the Maliwan Takedown.bl3hotfix
Swapped a Trooper out because they would become invincible at times.
=> Update Raid on the Maliwan Takedown.bl3hotfix

Stygian Emperor/Moze/Reactive Armor/60% Resistance Branch/README.md, Stygian Emperor/Moze/Reactive Armor/60% Resistance Branch/StygianEmperor_Moze_ReactiveArmor_60resist.bl3hotfix
Increases resistances dramatically (apparently in an attempt to negate self-damage). Made by request.
It's been a while, so there's a decent chance I forgot a step, or something.
=> New cheat branch of Reactive Armor

Stygian Emperor/Moze/SmartBear/README.md, Stygian Emperor/Moze/SmartBear/StygianEmperor_SmartBear.bl3hotfix
Mod makes Iron Cub big. 
Again, it's been too long since I've done this, so while the mod itself was actually made quite a while ago and should be okay, I may have messed up the pull request process or the formatting somewhere.
=> Finally uploading SmartBear mod

hallowfiend/fastlevelling_mildlyspeedy.bl3hotfix
hi! finally figured out how to contribute, got damn.
anyways, hi, i'm nikolai, here's my mod - a simple xp rate change. my first hotfix, but not my first mod - i have already made 4 pakfile-only texture mods, though i'm not sure how would i implement them here since pakfile stuff still seems to be in its infancy. oh well. (all of them are up on nexusmods)
props to apocalyptech.
=> my first mod in this repo!

hallowfiend/hotfixes/do_unto_all.bl3hotfix, hallowfiend/hotfixes/hamartia.bl3hotfix
created for josh arachnica but they can be public aswell bc y not
=> 2 amara skill hotfixes

CZ47/QoL/Quick Change & Respec Keybind.bl3hotfix
Been a while, uploading a hotfixmod that alllows instant menuing to the Quick Change Station anywhere.
=> Create Quick Change & Respec Keybind.bl3hotfix
